### ISSUE TITLE
Some hyperlink is inaccessible 

### ISSUE THREAD

**Issue by q2333gh** [dfinity/pocketic#12]
in here : https://crates.io/crates/pocket-ic
red marked is missing link
![image](https://github.com/dfinity/pocketic/assets/32679742/4572b6c3-8992-4e53-b97a-6dee4a9d682b)

**Comment by fxgst** [comment]
Thanks for pointing this out. Will be fixed in the next release!

**Comment by q2333gh** [comment]
Its not fixed yet
