### ISSUE TITLE
Will ` let pic = PocketIc::new();`  create a new  empty env every time?

### ISSUE THREAD

**Issue by q2333gh** [dfinity/pocketic#13]
Or i need to mannually exec `uninstall canister` to empty stable memory everytime ?

**Comment by q2333gh** [comment]
Or i need to mannually exec uninstall canister to empty stable memory everytime ?

**Comment by q2333gh** [comment]
I got it by using reinstall_canister().

**Comment by fxgst** [comment]
`let pic = PocketIC::new()` will always create a new IC instance with nothing installed and starting in a blank state.
