### ISSUE TITLE
Any plan to make a more detailed documentation of pocket-ic ? 

### ISSUE THREAD

**Issue by q2333gh** [dfinity/pocketic#14]
That will be so useful~

**Comment by fxgst** [comment]
If you want to know about the HTTP endpoints offered by the _server_, you can try out its endpoint `/api.json`, which will return an OpenAPI specification. You can then use tools like the [Swagger Editor](https://editor-next.swagger.io/) to display the returned JSON in a more human readable way.

If you want some documentation on PocketIC Rust, you can check out the [docs.rs](https://docs.rs/pocket-ic/2.2.0/pocket_ic/) documentation or the [how to guide](https://github.com/dfinity/ic/blob/master/packages/pocket-ic/HOWTO.md).

**Comment by q2333gh** [comment]
Got it . thanks
