### ISSUE TITLE
Cannot deploy via `dfx deploy ...` to pocket-ic replica that runs from CLI

### ISSUE THREAD

**Issue by ZenVoich** [dfinity/pocketic#4]
pocket-ic binary 2.0.1
dfx 0.15.2

I run pocket-ic by
```
$ pocket-ic -p 4943
2023-12-08T11:16:51.855200Z  INFO pocket_ic_server: The PocketIC server is listening on port 4943
```

Then I deploy by
```
$ dfx deploy main
Error: The replica returned an HTTP Error: Http Error: status 404 Not Found, content type "", content:
```

Same error for `dfx canister create main`.

Does replica REST API work on `pocket-ic`?

Also would be helpful to have documentation on how to use `pocket-ic` from CLI

**Comment by fxgst** [comment]
Hi @ZenVoich, dfx does currently not support deploying to PocketIC. To see an example setup, please look [here](https://github.com/dfinity/ic/blob/HEAD/packages/pocket-ic/tests/tests.rs#L19)

**Comment by ZenVoich** [comment]
Does this mean that pocket-ic now supports REST API?
