### ISSUE TITLE
Release binaries on GitHub?

### ISSUE THREAD

**Issue by ZenVoich** [dfinity/pocketic#5]
Hi. I'm currently adding toolchain version management to mops (moc, wasmtime, pocket-ic).

And it would be easier if there are will be binaries available on GitHub releases, so I can reuse logic which I use to download `moc` and `wasmtime` binaries.

Also no need to hardcode `version => hash` mapping for each version(and keep it up to date), but just rely on github release tag (latest or specific version tag)

**Comment by fxgst** [comment]
Hi @ZenVoich, we now publish all PocketIC binaries here on GitHub! Check them out in the Releases tab on the right.
cc @nathanosdev

**Comment by ZenVoich** [comment]
Great! Thank you @fxgst !
